USE [master]
GO

/****** Object:  Database [BDParqueo]    Script Date: 22/6/2022 1:19:25 ******/
DROP DATABASE [BDParqueo]
GO

/****** Object:  Database [BDParqueo]    Script Date: 22/6/2022 1:19:25 ******/
CREATE DATABASE [BDParqueo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDParqueo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDParqueo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDParqueo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDParqueo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDParqueo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDParqueo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDParqueo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDParqueo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDParqueo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDParqueo] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDParqueo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDParqueo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDParqueo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDParqueo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDParqueo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDParqueo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDParqueo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDParqueo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDParqueo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDParqueo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDParqueo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDParqueo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDParqueo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDParqueo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDParqueo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDParqueo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDParqueo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDParqueo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BDParqueo] SET  MULTI_USER 
GO

ALTER DATABASE [BDParqueo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDParqueo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDParqueo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDParqueo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BDParqueo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDParqueo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BDParqueo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BDParqueo] SET  READ_WRITE 
GO


